components:
  schemas:
    accommodation:
      
        properties:
          name:
            type: string
            required: true
            example: "The Blue Room"
          description:
            type: string
            required: true
            trim: true
            example: "this room is Blue!"
          maxGuests:
            type: number
            required: true
            example: 4
          city:
            type: string
            required: true
            example: London

GET /accommodation

will return the full list of accommodation
POST /accommodation

will add a new accommodation
400 if invalid data
GET /accommodation/:id

returns an existing accommodation
404 if not existing
PUT /accommodation/:id

will edit an existing accommodation
404 if not existing
DELETE /accommodation/:id

servers:
  - description: ''
    url: http://localhost:3000
openapi: 3.0.3
paths:
  '/accommodation':
    get:
      description: Returns a list of accommodations
      operationId: getAccommodation
      responses:
        '200':
          description: 'returns an array of accomodations'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/accommodation'
    post:
      description: This operation adds a new accommodation 
      operationId: addAccommodation
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/accommodation'
      responses:
        '201':
          description: Correctly added new accommodation
        '400':
          description: Bad request
    put: 

    delete:
      description: This operation checks out people from the room
      operationId: checkoutGuests
      parameters:
        - schema:
            $ref: '#/components/schemas/acc'
          in: path
          name: roomN
          required: true
      responses:
        '204':
          description: Correctly checked out people in the room
        '400':
          description: Bad post request
